# =========================================================
# Spring Boot
# =========================================================

spring.application.name=dashboard

server.port=8080


# =========================================================
# Application
# =========================================================

app.version=1.0.0

app.environment=${APP_ENVIRONMENT:Local Development}




# =========================================================
# EC2 Hostname
# =========================================================
#
# GitHub Actions passes the actual EC2 hostname using:
#
# APP_HOSTNAME=ip-10-0-1-181
#
# If running locally, it displays "Local Machine".
#

app.hostname=${APP_HOSTNAME:Local Machine}



# =========================================================
# Thymeleaf
# =========================================================

spring.thymeleaf.cache=false


# =========================================================
# Actuator
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.endpoints.web.base-path=/actuator


# =========================================================
# Application Info
# =========================================================

info.app.name=Cloud DevOps Dashboard
info.app.version=${app.version}
info.app.environment=${app.environment}

# =========================================================
# Grafana
# =========================================================

app.grafana-url=http://100.61.26.35:3000/d/adzp8hk/spring-boot-monitoring